---
title: "Initial Data Exploration"
author: "Victoria Hermanson"
format: html
editor: visual
---

## Cleaning dates/times

The first two digits are dates and the next four digits are time. Converting the text to a date/time object. For more info see [EDI](https://portal.edirepository.org/nis/metadataviewer?packageid=knb-lter-pal.95.5).

```{r}
#| label: read-csv

library(tidyverse)
seabird_95 <- read_csv(here::here("data/Cruise_Transect_Observations_merged.csv"))

#| label: renaming column headers
colnames(seabird_95) <- c("study","cruisename","year-month","station","eventnumber",
                          "depth","latitude","longitude", "day-time","seastate","salinity",
                          "flurorometry","windspeed","winddirection","habitat","icecover", 
                          "icetype","icecolor","countminute","species","number","linkages",
                          "behavior","direction","notes")

# seabird_95 %>% 
#   select(`year-month, `day-time`)
```

```{r}
#| label: cleaning-dates-times

library(lubridate)
lter_datetime <- function(ym, dhm) {
  year2 <- as.numeric(substr(ym, 1, 2))
  year4 <- ifelse(year2 > 90, 1900 + year2, 2000 + year2)
  dhm6 <- ifelse(str_length(dhm) == 5, paste0("0", dhm), dhm)
  ymd_hm(paste0(year4, substr(ym, 3, 4), dhm6), tz = "UTC")
}
seabird_95_datetime <- seabird_95 %>% 
  mutate(sighting_utc = lter_datetime(`year-month`, `day-time`))
    #sighting_utc = ymd_hm(paste(`Year / Month`, `Day / Time`), tz = "UTC"))
```

359 rows failed to parse. Here's what they look like. It looks like some of the dates are \>31.

```{r}
#| label: datetime-errors

seabird_95_datetime %>% 
  select(`eventnumber`, `year-month`, `day-time`, sighting_utc) %>% 
  filter(is.na(sighting_utc)) %>% 
  DT::datatable()

# 3 digits for julian day, 2 digits for hour, 2 digits for min

```

Lat/long exploration.

```{r}


```
